/**
 * Copies the licensed WOFF2 files this site uses out of the installed
 * @fontsource packages into public/fonts/, and generates src/styles/fonts.css.
 *
 * Fonts are self-hosted: nothing is requested from Google Fonts at runtime.
 * Both families are SIL Open Font License 1.1; the licence files are copied
 * next to the fonts. Run with `npm run fonts`.
 *
 * Weights come from the handoff, plus Space Grotesk 600, which the design uses
 * for card, step and ProjectFlow titles (audit D03).
 */
import { mkdir, copyFile, writeFile, readFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const outDir = path.join(root, 'public', 'fonts');
const SUBSETS = ['latin', 'latin-ext'];

const FAMILIES = [
  { pkg: '@fontsource/space-grotesk', family: 'Space Grotesk', file: 'space-grotesk', weights: [500, 600, 700] },
  { pkg: '@fontsource/ibm-plex-sans', family: 'IBM Plex Sans', file: 'ibm-plex-sans', weights: [400, 500, 600] },
  { pkg: '@fontsource/ibm-plex-mono', family: 'IBM Plex Mono', file: 'ibm-plex-mono', weights: [400, 500] },
];

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const blocks = [
  '/*',
  ' * Generated by scripts/sync-fonts.mjs. Do not edit by hand.',
  ' * Self-hosted WOFF2, SIL Open Font License 1.1 (see public/fonts/*-LICENSE.txt).',
  ' */',
  '',
];
let copied = 0;

for (const entry of FAMILIES) {
  const pkgDir = path.join(root, 'node_modules', entry.pkg);
  const unicode = JSON.parse(await readFile(path.join(pkgDir, 'unicode.json'), 'utf8'));
  await copyFile(path.join(pkgDir, 'LICENSE'), path.join(outDir, `${entry.file}-LICENSE.txt`));

  for (const weight of entry.weights) {
    for (const subset of SUBSETS) {
      const name = `${entry.file}-${subset}-${weight}-normal.woff2`;
      const src = path.join(pkgDir, 'files', name);
      if (!existsSync(src)) throw new Error(`Missing font file: ${src}`);
      await copyFile(src, path.join(outDir, name));
      copied += 1;
      blocks.push(
        '@font-face {',
        `  font-family: '${entry.family}';`,
        '  font-style: normal;',
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url('/fonts/${name}') format('woff2');`,
        `  unicode-range: ${unicode[subset]};`,
        '}',
        '',
      );
    }
  }
}

await writeFile(path.join(root, 'src', 'styles', 'fonts.css'), blocks.join('\n'), 'utf8');
console.log(`Copied ${copied} woff2 files to public/fonts and wrote src/styles/fonts.css`);
